<a href="https://colab.research.google.com/github/diro5t/deep_quadric_learning/blob/main/TestTinyGrad.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Install tinygrad

In [ ]:
%cd /content

/content


In [ ]:
import shutil
shutil.rmtree('tinygrad')

In [ ]:
!git clone https://github.com/geohot/tinygrad.git

Cloning into 'tinygrad'...
remote: Enumerating objects: 14716, done.
remote: Counting objects: 100% (4132/4132), done.
remote: Compressing objects: 100% (387/387), done.
remote: Total 14716 (delta 3830), reused 3763 (delta 3742), pack-reused 10584
Receiving objects: 100% (14716/14716), 18.38 MiB | 36.40 MiB/s, done.
Resolving deltas: 100% (10508/10508), done.


In [ ]:
%cd tinygrad

/content/tinygrad


In [ ]:
!python3 -m pip install -e .

Obtaining file:///content/tinygrad
  Preparing metadata (setup.py) ... done
  Running setup.py develop for tinygrad


In [ ]:
!pip show tinygrad

Name: tinygrad
Version: 0.6.0
Summary: You like pytorch? You like micrograd? You love tinygrad! <3
Home-page: 
Author: George Hotz
Author-email: 
License: MIT
Location: /content/tinygrad
Editable project location: /content/tinygrad
Requires: networkx, numpy, pillow, pyopencl, PyYAML, requests, tqdm
Required-by: 


### Test it

In [ ]:
from tinygrad.tensor import Tensor
x = Tensor.eye(3, requires_grad=True)
y = Tensor([[2.0,0,-2.0]], requires_grad=True)
z = y.matmul(x).sum()
z.backward()

print(x.grad.numpy())  # dz/dx
print(y.grad.numpy())  # dz/dy

[[ 2.  2.  2.]
 [ 0.  0.  0.]
 [-2. -2. -2.]]
[[1. 1. 1.]]
